[custom]

;设置分组标志位
custom_proxy_group=
custom_proxy_group=
custom_proxy_group=
custom_proxy_group=
custom_proxy_group=
custom_proxy_group=
custom_proxy_group=
custom_proxy_group=
custom_proxy_group=
custom_proxy_group=
custom_proxy_group=
custom_proxy_group=
custom_proxy_group=
